"use client"

import { useRef } from "react"
import { motion, useScroll, useTransform } from "framer-motion"
import { ArrowRight, Coins, TrendingUp, Layers, Clock, Globe, Lock } from "lucide-react"

import { Button } from "@/components/ui/button"
import { FeatureCard } from "@/components/ui/feature-card"
import { SectionHeading } from "@/components/ui/section-heading"

export default function OutStakePage() {
  const { scrollYProgress } = useScroll()
  const containerRef = useRef<HTMLDivElement>(null)

  const titleOpacity = useTransform(scrollYProgress, [0, 0.1], [1, 0.8])
  const titleY = useTransform(scrollYProgress, [0, 0.1], [0, -20])

  return (
    <div ref={containerRef} className="relative flex flex-col min-h-screen">
      {/* Hero Section */}
      <section className="hero-section relative overflow-hidden">
        <div className="hero-background fixed inset-0 w-full h-full -z-20"></div>
        <div className="hero-content-wrapper">
          <div className="container px-4 md:px-6 mx-auto pt-24 pb-12">
            <div className="flex flex-col items-center text-center space-y-12">
              <motion.div
                initial={{ y: 20 }}
                animate={{ y: 0 }}
                transition={{ duration: 0.8 }}
                className="space-y-6 max-w-4xl"
              >
                <div className="inline-block mb-6">
                  <div className="relative">
                    <div className="absolute inset-0 blur-xl bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600 opacity-70 rounded-full" />
                    <div className="relative px-6 py-2 bg-black/65 backdrop-blur-sm border border-white/10 rounded-full text-sm font-medium text-white">
                      Yield Tokenization
                    </div>
                  </div>
                </div>

                <h1 className="text-5xl md:text-7xl lg:text-8xl font-bold tracking-tighter bg-clip-text text-transparent bg-gradient-to-r from-purple-500 via-pink-500 to-blue-500 drop-shadow-[0_0_15px_rgba(168,85,247,0.5)]">
                  OutStake
                </h1>

                <p className="text-xl md:text-2xl text-zinc-300 max-w-3xl mx-auto leading-relaxed">
                  A protocol built entirely around yield-bearing tokens, introducing the first non-USD stablecoin model
                  tied to yield rates.
                </p>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5, delay: 0.3 }}
                className="flex flex-col sm:flex-row gap-4"
              >
                <Button
                  size="lg"
                  className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white border-0 rounded-full px-8 h-12 text-base shadow-[0_0_15px_rgba(168,85,247,0.5)]"
                >
                  Start Staking
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.6 }}
                className="pt-6 w-full max-w-5xl"
              >
                <div className="relative h-12 md:h-16">
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="w-full h-px bg-gradient-to-r from-transparent via-white/20 to-transparent" />
                  </div>
                  <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 bg-black/50 backdrop-blur-md px-6 py-2 rounded-full border border-white/10">
                    <p className="text-zinc-400 text-sm">Scroll to explore</p>
                  </div>
                </div>
              </motion.div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 md:py-24 container px-4 md:px-6 mx-auto relative z-10">
        <div className="absolute inset-0 bg-grid-pattern bg-center opacity-5" />

        <SectionHeading
          title="Key Features"
          description="OutStake offers greater flexibility, enhanced composability, and higher returns compared to other yield token protocols."
          gradient="from-purple-400 to-pink-500"
          align="center"
          className="mb-16"
        />

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12">
          <FeatureCard
            title="Novel Staking Model"
            description="Controls yields generated by yield-bearing tokens and unlocks liquidity of staked assets with an eternal lifecycle for enhanced token utility."
            bulletPoints={[
              "Novel design different from market",
              "Unlocks liquidity of staked assets",
              "Eternal lifecycle with no expiration dates",
            ]}
            icon={<Coins className="h-6 w-6 text-purple-500" />}
            color="#a855f7"
            delay={0.1}
            className="bg-black/60 backdrop-blur-sm"
          />

          <FeatureCard
            title="Enhanced Composability"
            description="Standard ERC20 tokens with no expiration dates allow for seamless integration with other DeFi protocols and applications."
            bulletPoints={[
              "Freely integrated into other DeFi protocols",
              "Shared liquidity across yield-bearing tokens",
              "Powerful network effect ecosystem",
            ]}
            icon={<Globe className="h-6 w-6 text-purple-500" />}
            color="#a855f7"
            delay={0.2}
            className="bg-black/60 backdrop-blur-sm"
          />

          <FeatureCard
            title="Multiple Income Streams"
            description="Earn from both yield generated by deposits and additional income from trading YT tokens correlated with yield rates."
            bulletPoints={[
              "Higher returns than other protocols",
              "YT value tied directly to yield rates",
              "Fixed yield rates through SP tokens",
            ]}
            icon={<TrendingUp className="h-6 w-6 text-purple-500" />}
            color="#a855f7"
            delay={0.3}
            className="bg-black/60 backdrop-blur-sm"
          />

          <FeatureCard
            title="Omnichain Capability"
            description="Universal Principal Token (UPT) enables seamless transfers across different blockchains through LayerZero integration."
            bulletPoints={[
              "Cross-chain asset transfers",
              "Amplified network effects",
              "Shared liquidity across blockchains",
            ]}
            icon={<Layers className="h-6 w-6 text-purple-500" />}
            color="#a855f7"
            delay={0.4}
            className="bg-black/60 backdrop-blur-sm"
          />

          <FeatureCard
            title="Flexible Staking Duration"
            description="Users can freely select staking duration, controlling the amount of PT minted and making position expiration time a tradable asset."
            bulletPoints={[
              "User-controlled staking periods",
              "Tradable staking positions (SP)",
              "No forced lock-up periods",
            ]}
            icon={<Clock className="h-6 w-6 text-purple-500" />}
            color="#a855f7"
            delay={0.5}
            className="bg-black/60 backdrop-blur-sm"
          />

          <FeatureCard
            title="Non-USD Stablecoin Model"
            description="First non-USD stablecoin model tied to yield rates, allowing users to take long or short positions on yield rates."
            bulletPoints={[
              "YT serves as yield rate stablecoin",
              "Mitigated risk of price manipulation",
              "Decentralized yield rate trading",
            ]}
            icon={<Lock className="h-6 w-6 text-purple-500" />}
            color="#a855f7"
            delay={0.6}
            className="bg-black/60 backdrop-blur-sm"
          />
        </div>
      </section>

      {/* How It Works */}
      <section className="py-10 md:py-16 relative">
        <div className="container px-4 md:px-6 mx-auto relative">
          <SectionHeading
            title="How OutStake Works"
            description="OutStake splits yield-bearing tokens into multiple components, unlocking new possibilities for DeFi."
            gradient="from-purple-400 to-blue-500"
            align="center"
            className="mb-16"
          />

          {/* 流程图 - 完全重新设计 */}
          <div className="max-w-5xl mx-auto">
            {/* 步骤1 */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              viewport={{ once: true }}
              className="relative mb-8"
            >
              <div className="relative bg-black/70 backdrop-blur-sm rounded-xl border border-purple-500/20 overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-purple-600 to-pink-600"></div>
                <div className="p-6 md:p-8">
                  <div className="flex items-center mb-4">
                    <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gradient-to-r from-purple-600 to-pink-600 text-white font-bold text-lg mr-4">
                      1
                    </div>
                    <h3 className="text-2xl font-bold text-white inline-flex">Deposit Assets</h3>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="col-span-1 md:col-span-2">
                      <p className="text-zinc-300 mb-4">
                        Users deposit yield-bearing tokens (like stETH, RWA) or underlying assets (like ETH) into the
                        OutStake protocol.
                      </p>

                      <div className="flex flex-wrap gap-2 mb-4">
                        <div className="px-3 py-1.5 bg-black/40 rounded-md border border-white/10 flex items-center">
                          <div className="w-3 h-3 rounded-full bg-blue-500 mr-2"></div>
                          <span className="text-zinc-300">stETH</span>
                        </div>
                        <div className="px-3 py-1.5 bg-black/40 rounded-md border border-white/10 flex items-center">
                          <div className="w-3 h-3 rounded-full bg-green-500 mr-2"></div>
                          <span className="text-zinc-300">RWA</span>
                        </div>
                        <div className="px-3 py-1.5 bg-black/40 rounded-md border border-white/10 flex items-center">
                          <div className="w-3 h-3 rounded-full bg-yellow-500 mr-2"></div>
                          <span className="text-zinc-300">ETH</span>
                        </div>
                      </div>

                      <div className="text-sm text-zinc-400">
                        <span className="text-purple-400">Example:</span> Deposit 10 stETH that's already earning ~3.5%
                        APR on Lido
                      </div>
                    </div>

                    <div className="bg-gradient-to-br from-purple-900/40 to-blue-900/40 rounded-lg border border-purple-500/20 h-full flex flex-col">
                      <div className="flex-1 flex flex-col justify-center p-4">
                        <div className="text-sm text-purple-300 font-medium mb-2 inline-block">
                          What are yield-bearing tokens?
                        </div>
                        <p className="text-white text-sm">
                          Tokens that generate yield or have potential yield. Examples include stETH(Lido),
                          sUSDE(Ethena), Stone(StakeStone), and LP tokens.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* 连接箭头 */}
            <div className="flex justify-center my-4">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M12 5L12 19M12 19L5 12M12 19L19 12"
                  stroke="url(#arrow-gradient)"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <defs>
                  <linearGradient id="arrow-gradient" x1="12" y1="19" x2="12" y2="5" gradientUnits="userSpaceOnUse">
                    <stop stopColor="#9333EA" />
                    <stop offset="1" stopColor="#EC4899" />
                  </linearGradient>
                </defs>
              </svg>
            </div>

            {/* 步骤2 */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              viewport={{ once: true }}
              className="relative mb-8"
            >
              <div className="relative bg-black/70 backdrop-blur-sm rounded-xl border border-blue-500/20 overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-blue-600 to-cyan-600"></div>
                <div className="p-6 md:p-8">
                  <div className="flex items-center mb-4">
                    <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gradient-to-r from-blue-600 to-cyan-600 text-white font-bold text-lg mr-4">
                      2
                    </div>
                    <h3 className="text-2xl font-bold text-white inline-flex">Standardize Yield (SY)</h3>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="col-span-1 md:col-span-2">
                      <p className="text-zinc-300 mb-4">
                        The protocol wraps yield-bearing tokens into Standardized Yield (SY) tokens based on the ERC5115
                        standard, providing a unified interface for all yield-bearing tokens. This process happens
                        automatically behind the scenes.
                      </p>

                      <div className="bg-black/40 rounded-lg p-4 border border-white/5 mb-4">
                        <div className="font-mono text-sm">
                          <span className="text-zinc-300">wstETH</span>
                          <span className="text-zinc-500 mx-2">→</span>
                          <span className="text-cyan-400">SY-wstETH</span>
                        </div>
                      </div>

                      <div className="text-sm text-zinc-400">
                        <span className="text-blue-400">Example:</span> 10 wstETH is wrapped into 10 SY-wstETH
                      </div>
                    </div>

                    <div className="bg-gradient-to-br from-blue-900/40 to-cyan-900/40 rounded-lg border border-blue-500/20 h-full flex flex-col">
                      <div className="flex-1 flex flex-col justify-center p-4">
                        <div className="text-sm text-blue-300 font-medium mb-2 inline-block">What is SY?</div>
                        <p className="text-white text-sm">
                          SY is a vault token based on the ERC5115 standard designed to encapsulate yield-bearing
                          tokens. It provides a standardized interface for interacting with any yield-generating
                          mechanism.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* 连接箭头 */}
            <div className="flex justify-center my-4">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M12 5L12 19M12 19L5 12M12 19L19 12"
                  stroke="url(#arrow-gradient-2)"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <defs>
                  <linearGradient id="arrow-gradient-2" x1="12" y1="19" x2="12" y2="5" gradientUnits="userSpaceOnUse">
                    <stop stopColor="#2563EB" />
                    <stop offset="1" stopColor="#06B6D4" />
                  </linearGradient>
                </defs>
              </svg>
            </div>

            {/* 步骤3 */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              viewport={{ once: true }}
              className="relative mb-8"
            >
              <div className="relative bg-black/70 backdrop-blur-sm rounded-xl border border-pink-500/20 overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-pink-600 to-purple-600"></div>
                <div className="p-6 md:p-8">
                  <div className="flex items-center mb-4">
                    <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gradient-to-r from-pink-600 to-purple-600 text-white font-bold text-lg mr-4">
                      3
                    </div>
                    <h3 className="text-2xl font-bold text-white inline-flex">Stake & Lock SY Tokens</h3>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="col-span-1 md:col-span-2">
                      <p className="text-zinc-300 mb-4">
                        Users stake their SY tokens and specify a lock-up period. This process mints three types of
                        tokens, each representing different aspects of the yield-bearing token.
                      </p>

                      <div className="grid grid-cols-3 gap-3 mb-4">
                        <div className="bg-purple-900/30 rounded-lg p-3 border border-purple-500/20">
                          <div className="text-center mb-1">
                            <span className="text-purple-400 font-bold">PT</span>
                          </div>
                          <p className="text-xs text-zinc-400 text-center">Principal Token</p>
                        </div>
                        <div className="bg-pink-900/30 rounded-lg p-3 border border-pink-500/20">
                          <div className="text-center mb-1">
                            <span className="text-pink-400 font-bold">YT</span>
                          </div>
                          <p className="text-xs text-zinc-400 text-center">Yield Rate Token</p>
                        </div>
                        <div className="bg-blue-900/30 rounded-lg p-3 border border-blue-500/20">
                          <div className="text-center mb-1">
                            <span className="text-blue-400 font-bold">PYT</span>
                          </div>
                          <p className="text-xs text-zinc-400 text-center">Points Yield Token</p>
                        </div>
                      </div>

                      <div className="bg-black/40 rounded-lg p-4 border border-white/5 mb-4">
                        <div className="font-mono text-sm">
                          <span className="text-cyan-400">SY-sUSDE</span>
                          <span className="text-zinc-500 mx-2">→</span>
                          <span className="text-purple-400">PT-sUSDE</span>
                          <span className="text-zinc-500 mx-1">+</span>
                          <span className="text-pink-400">YT-sUSDE</span>
                          <span className="text-zinc-500 mx-1">+</span>
                          <span className="text-blue-400">PYT-sUSDE</span>
                        </div>
                      </div>

                      <div className="text-sm text-zinc-400">
                        <span className="text-pink-400">Example:</span> 10 SY-sUSDE with a 100 days lock generates 9.8
                        PT-sUSDE, 1000 YT-sUSDE, and 1 PYT-sUSDE
                      </div>
                    </div>

                    <div className="space-y-4 h-full flex flex-col justify-center">
                      <div className="bg-gradient-to-r from-purple-900/40 to-purple-800/40 rounded-lg border border-purple-500/30 p-3">
                        <div className="text-sm text-purple-300 font-semibold mb-1 inline-block">
                          PT (Principal Token)
                        </div>
                        <p className="text-xs text-white">
                          Represents the principal portion of yield-bearing tokens. Can be encapsulated as SP.
                        </p>
                      </div>

                      <div className="bg-gradient-to-r from-pink-900/40 to-pink-800/40 rounded-lg border border-pink-500/30 p-3">
                        <div className="text-sm text-pink-300 font-semibold mb-1 inline-block">
                          YT (Yield Rate Token)
                        </div>
                        <p className="text-xs text-white">
                          Represents ownership of all yield generated by the underlying assets. Has no expiration date,
                          unlike other protocols.
                        </p>
                      </div>

                      <div className="bg-gradient-to-r from-blue-900/40 to-blue-800/40 rounded-lg border border-blue-500/30 p-3">
                        <div className="text-sm text-blue-300 font-semibold mb-1 inline-block">
                          PYT (Points Yield Token)
                        </div>
                        <p className="text-xs text-white">Represents external protocol points yields (if available).</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* 连接箭头 */}
            <div className="flex justify-center my-4">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M12 5L12 19M12 19L5 12M12 19L19 12"
                  stroke="url(#arrow-gradient-3)"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <defs>
                  <linearGradient id="arrow-gradient-3" x1="12" y1="19" x2="12" y2="5" gradientUnits="userSpaceOnUse">
                    <stop stopColor="#9333EA" />
                    <stop offset="1" stopColor="#DB2777" />
                  </linearGradient>
                </defs>
              </svg>
            </div>

            {/* 步骤4 */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
              viewport={{ once: true }}
              className="relative mb-8"
            >
              <div className="relative bg-black/70 backdrop-blur-sm rounded-xl border border-green-500/20 overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-green-600 to-cyan-600"></div>
                <div className="p-6 md:p-8">
                  <div className="flex items-center mb-4">
                    <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gradient-to-r from-green-600 to-cyan-600 text-white font-bold text-lg mr-4">
                      4
                    </div>
                    <h3 className="text-2xl font-bold text-white inline-flex">Encapsulate PT into SP (Optional)</h3>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="col-span-1 md:col-span-2">
                      <p className="text-zinc-300 mb-4">
                        Users holding positions can encapsulate PT tokens, thereby minting the position and PT tokens
                        into transferable SP (Staking Position) tokens, representing the right to redeem the principal
                        upon position maturity.
                      </p>

                      <div className="bg-black/40 rounded-lg p-4 border border-white/5 mb-4">
                        <div className="font-mono text-sm">
                          <span className="text-purple-400">PT-stETH</span>
                          <span className="text-zinc-500 mx-2">→</span>
                          <span className="text-green-400">SP-stETH</span>
                        </div>
                      </div>
                    </div>

                    <div className="bg-gradient-to-br from-green-900/40 to-cyan-900/40 rounded-lg border border-green-500/20 h-full flex flex-col">
                      <div className="flex-1 flex flex-col justify-center p-4">
                        <div className="text-sm text-green-300 font-medium mb-2 inline-block">What is SP?</div>
                        <p className="text-white text-sm">
                          SP is a token based on the ERC6909 standard used to encapsulate staked positions. It
                          represents ownership of principal redemption rights upon maturity, creating fixed-rate returns
                          based on its trading price.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* 连接箭头 */}
            <div className="flex justify-center my-4">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M12 5L12 19M12 19L5 12M12 19L19 12"
                  stroke="url(#arrow-gradient-4)"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <defs>
                  <linearGradient id="arrow-gradient-4" x1="12" y1="19" x2="12" y2="5" gradientUnits="userSpaceOnUse">
                    <stop stopColor="#059669" />
                    <stop offset="1" stopColor="#0891B2" />
                  </linearGradient>
                </defs>
              </svg>
            </div>

            {/* 步骤5 */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.4 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="relative bg-black/70 backdrop-blur-sm rounded-xl border border-purple-500/20 overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-purple-600 to-blue-600"></div>
                <div className="p-6 md:p-8">
                  <div className="flex items-center mb-4">
                    <div className="flex items-center justify-center w-10 h-10 rounded-full bg-gradient-to-r from-purple-600 to-blue-600 text-white font-bold text-lg mr-4">
                      5
                    </div>
                    <h3 className="text-2xl font-bold text-white inline-flex">Multiple Income Streams</h3>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="col-span-1 md:col-span-2">
                      <p className="text-zinc-300 mb-4">
                        Users can now benefit from multiple income sources, each with different risk and return
                        profiles.
                      </p>

                      <div className="space-y-3 mb-4">
                        <div className="flex items-start">
                          <div className="w-6 h-6 rounded-full bg-pink-600/20 flex items-center justify-center mt-0.5 mr-3 flex-shrink-0">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              className="h-3 w-3 text-pink-400"
                              viewBox="0 0 24 24"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            >
                              <polyline points="20 6 9 17 4 12"></polyline>
                            </svg>
                          </div>
                          <div>
                            <div className="text-pink-400 font-medium">Trade YT tokens</div>
                            <p className="text-zinc-300 text-sm">
                              Earn from yield rate fluctuations. YT value increases over time as yield accumulates.
                            </p>
                          </div>
                        </div>

                        <div className="flex items-start">
                          <div className="w-6 h-6 rounded-full bg-green-600/20 flex items-center justify-center mt-0.5 mr-3 flex-shrink-0">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              className="h-3 w-3 text-green-400"
                              viewBox="0 0 24 24"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            >
                              <polyline points="20 6 9 17 4 12"></polyline>
                            </svg>
                          </div>
                          <div>
                            <div className="text-green-400 font-medium">Sell SP tokens</div>
                            <p className="text-zinc-300 text-sm">
                              Get fixed-rate returns before maturity by trading SP tokens on the market.
                            </p>
                          </div>
                        </div>

                        <div className="flex items-start">
                          <div className="w-6 h-6 rounded-full bg-blue-600/20 flex items-center justify-center mt-0.5 mr-3 flex-shrink-0">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              className="h-3 w-3 text-blue-400"
                              viewBox="0 0 24 24"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            >
                              <polyline points="20 6 9 17 4 12"></polyline>
                            </svg>
                          </div>
                          <div>
                            <div className="text-blue-400 font-medium">Utilize PYT tokens</div>
                            <p className="text-zinc-300 text-sm">
                              Benefit from external protocol points rewards through PYT tokens.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="bg-gradient-to-br from-purple-800/50 to-blue-800/50 rounded-lg border border-purple-500/30 h-full flex flex-col">
                      <div className="flex-1 flex flex-col justify-center p-4">
                        <div className="text-sm text-purple-200 font-semibold mb-2 inline-block">
                          OutStake's Unique Advantage
                        </div>
                        <p className="text-white text-sm mb-3">
                          Unlike other protocols, OutStake's tokens have no expiration dates, allowing for greater
                          composability and liquidity in the DeFi ecosystem.
                        </p>
                        <div className="text-xs text-blue-200">
                          YT serves as the first non-USD stablecoin model tied to yield rates, enabling users to take
                          positions on yield rate movements.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>

          {/* Token Cards - Simplified */}
          <div className="mt-16">
            <h3 className="text-2xl font-bold text-center text-white mb-8">OutStake Token Ecosystem</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                viewport={{ once: true }}
                className="group"
              >
                <div className="relative h-full">
                  <div className="absolute -inset-1 rounded-xl bg-gradient-to-r from-purple-600/30 to-purple-600/10 opacity-70 group-hover:opacity-100 blur-sm transition duration-300"></div>
                  <div className="relative h-full bg-black/70 backdrop-blur-sm rounded-xl border border-purple-500/20 p-6 overflow-hidden group-hover:border-purple-500/40 transition duration-300">
                    <div className="absolute -right-8 -top-8 w-24 h-24 rounded-full bg-purple-600/10"></div>
                    <div className="flex items-center mb-4">
                      <div className="w-10 h-10 rounded-full bg-purple-600/20 flex items-center justify-center mr-3">
                        <span className="text-purple-400 font-bold">PT</span>
                      </div>
                      <h4 className="text-xl font-bold text-white">Principal Token</h4>
                    </div>
                    <p className="text-zinc-300 text-sm leading-relaxed">
                      Represents the principal portion of yield-bearing tokens. PT has no expiration date, allowing for
                      greater composability with other DeFi protocols.
                    </p>
                    <div className="mt-4 pt-4 border-t border-white/5">
                      <div className="text-xs text-zinc-400 uppercase tracking-wider mb-2">Key Features</div>
                      <div className="flex flex-wrap gap-2">
                        <span className="px-2 py-1 bg-purple-900/20 rounded-md text-xs text-purple-400">
                          No Expiration
                        </span>
                        <span className="px-2 py-1 bg-purple-900/20 rounded-md text-xs text-purple-400">
                          ERC20 Standard
                        </span>
                        <span className="px-2 py-1 bg-purple-900/20 rounded-md text-xs text-purple-400">
                          Redeemable
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.1 }}
                viewport={{ once: true }}
                className="group"
              >
                <div className="relative h-full">
                  <div className="absolute -inset-1 rounded-xl bg-gradient-to-r from-pink-600/30 to-pink-600/10 opacity-70 group-hover:opacity-100 blur-sm transition duration-300"></div>
                  <div className="relative h-full bg-black/70 backdrop-blur-sm rounded-xl border border-pink-500/20 p-6 overflow-hidden group-hover:border-pink-500/40 transition duration-300">
                    <div className="absolute -right-8 -top-8 w-24 h-24 rounded-full bg-pink-600/10"></div>
                    <div className="flex items-center mb-4">
                      <div className="w-10 h-10 rounded-full bg-pink-600/20 flex items-center justify-center mr-3">
                        <span className="text-pink-400 font-bold">YT</span>
                      </div>
                      <h4 className="text-xl font-bold text-white">Yield Rate Token</h4>
                    </div>
                    <p className="text-zinc-300 text-sm leading-relaxed">
                      Represents ownership of all yield generated by the underlying assets. YT's value increases over
                      time as the yield pool accumulates, creating a non-USD stablecoin tied to yield rates.
                    </p>
                    <div className="mt-4 pt-4 border-t border-white/5">
                      <div className="text-xs text-zinc-400 uppercase tracking-wider mb-2">Key Features</div>
                      <div className="flex flex-wrap gap-2">
                        <span className="px-2 py-1 bg-pink-900/20 rounded-md text-xs text-pink-400">
                          Yield Correlated
                        </span>
                        <span className="px-2 py-1 bg-pink-900/20 rounded-md text-xs text-pink-400">
                          Universal Token
                        </span>
                        <span className="px-2 py-1 bg-pink-900/20 rounded-md text-xs text-pink-400">No Expiration</span>
                      </div>
                    </div>
                  </div>
                </div>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.2 }}
                viewport={{ once: true }}
                className="group"
              >
                <div className="relative h-full">
                  <div className="absolute -inset-1 rounded-xl bg-gradient-to-r from-green-600/30 to-green-600/10 opacity-70 group-hover:opacity-100 blur-sm transition duration-300"></div>
                  <div className="relative h-full bg-black/70 backdrop-blur-sm rounded-xl border border-green-500/20 p-6 overflow-hidden group-hover:border-green-500/40 transition duration-300">
                    <div className="absolute -right-8 -top-8 w-24 h-24 rounded-full bg-green-600/10"></div>
                    <div className="flex items-center mb-4">
                      <div className="w-10 h-10 rounded-full bg-green-600/20 flex items-center justify-center mr-3">
                        <span className="text-green-400 font-bold">SP</span>
                      </div>
                      <h4 className="text-xl font-bold text-white">Staking Position</h4>
                    </div>
                    <p className="text-zinc-300 text-sm leading-relaxed">
                      An ERC6909 token that encapsulates staked positions. SP represents ownership of principal
                      redemption rights upon maturity, creating fixed-rate returns based on trading price.
                    </p>
                    <div className="mt-4 pt-4 border-t border-white/5">
                      <div className="text-xs text-zinc-400 uppercase tracking-wider mb-2">Key Features</div>
                      <div className="flex flex-wrap gap-2">
                        <span className="px-2 py-1 bg-green-900/20 rounded-md text-xs text-green-400">
                          Transferable
                        </span>
                        <span className="px-2 py-1 bg-green-900/20 rounded-md text-xs text-green-400">Fixed Rate</span>
                        <span className="px-2 py-1 bg-green-900/20 rounded-md text-xs text-green-400">ERC6909</span>
                      </div>
                    </div>
                  </div>
                </div>
              </motion.div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 md:py-32 relative">
        <div className="container px-4 md:px-6 mx-auto">
          <div className="max-w-5xl mx-auto">
            <div className="relative overflow-hidden rounded-3xl">
              <div className="absolute inset-0 bg-gradient-to-r from-purple-600/40 via-pink-600/40 to-blue-600/40" />
              <div className="absolute inset-0 bg-[url('/grid.svg')] bg-center opacity-25" />
              <div className="relative p-8 md:p-12 lg:p-16">
                <div className="text-center max-w-3xl mx-auto">
                  <h2 className="text-3xl md:text-4xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-purple-400 via-pink-500 to-blue-500 mb-6">
                    Ready to Start Earning with OutStake?
                  </h2>
                  <p className="text-zinc-300 text-lg leading-relaxed mb-8">
                    Join the OutStake protocol today and start earning higher returns with our innovative yield-bearing
                    token model.
                  </p>
                  <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                    <Button
                      size="lg"
                      className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white border-0 rounded-full px-8 h-12 text-base w-40 flex items-center justify-center shadow-[0_0_15px_rgba(168,85,247,0.5)]"
                    >
                      Launch App
                    </Button>
                    <Button
                      size="lg"
                      className="bg-gradient-to-r from-pink-500 to-blue-600 hover:from-pink-600 hover:to-blue-700 text-white border-0 rounded-full px-8 h-12 text-base w-40 flex items-center justify-center shadow-[0_0_15px_rgba(219,39,119,0.5)]"
                      onClick={() =>
                        window.open("https://outrun.gitbook.io/doc/outstake", "_blank", "noopener,noreferrer")
                      }
                    >
                      Read Doc
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
